# Jekyll Configuration

title: Mathlib Reviewer Bootcamp 2026
description: A week-long workshop for expert reviewers of Mathlib
url: https://yaeldillies.github.io
baseurl: /

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
