# Jekyll Configuration

title: YaÃ«l Dillies's webpage
description: Additive combinatorics and formalisation
url: https://yaeldillies.github.io
baseurl: /

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
